development:
  stripe_secret_key: 'sk_test_51H9voND7h6J7ftZvAGKouN9h8Uj0B1VpYt1XZsOKznHx86objQQOB5cwCZFwnX4T8Pq0NCjMcdhe06LiuHxUlVvs00RYDjadPE'
  stripe_publishable_key: 'pk_test_51H9voND7h6J7ftZvWesW0Ak9dpg5Q6sKyjwG6KgHgkmToaqJQC7QcS25pr9PRGekpAwIgKIfliVBw71q4IsCApyw00KxLMKKCD'